services:
  db:
    image: postgres:18-alpine
    container_name: brio_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-runtime
    container_name: brio_django_web
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate && 
             gunicorn --bind 0.0.0.0:8000 brio_backend.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-final
    container_name: brio_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Проброс SSL сертификатов с хост-машины в контейнер.
      # Эти тома будут использоваться только если USE_SSL=true в .env.
      # Docker создаст пустые папки, если файлы не найдены, но Nginx не упадет,
      # так как entrypoint.sh сгенерирует конфиг без SSL.
      - ${SSL_CERTIFICATE_PATH}:/etc/ssl/certs/fullchain.pem:ro
      - ${SSL_CERTIFICATE_KEY_PATH}:/etc/ssl/private/privkey.pem:ro
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - USE_SSL=${USE_SSL}
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
