# Generated by Django 5.0.1 on 2026-01-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fio_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО (CN)'),
        ),
    ]
