# Конфигурация upstream для проксирования запросов к Django-приложению.
# 'web' - это имя сервиса Django в docker-compose.yml.
upstream django_server {
    server web:8000;
}

# Основная конфигурация сервера Nginx для локальной разработки.
server {
    # Прослушивание стандартного HTTP порта.
    listen 80;
    server_name localhost;
    charset utf-8;

    # Установка максимального размера загружаемого файла.
    client_max_body_size 20M;

    # Раздача медиафайлов, загруженных пользователями.
    # Nginx отдает их напрямую из общего тома.
    location /media/ {
        alias /app/mediafiles/;
    }

    # Раздача статических файлов (CSS, JS, изображения админки).
    # Nginx отдает их напрямую из общего тома,
    # который наполняется командой 'collectstatic'.
    location /static/ {
        alias /app/staticfiles/;
    }

    # Проксирование всех остальных запросов к Django-приложению.
    location / {
        proxy_pass http://django_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
