# Generated by Django 5.0.1 on 2025-12-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Артикул')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Дата КП')),
                ('category_1', models.CharField(blank=True, max_length=255, verbose_name='Категория Ур.1')),
                ('category_1_zh', models.CharField(blank=True, max_length=255, verbose_name='Категория Ур.1 (CN)')),
                ('category_2', models.CharField(blank=True, max_length=255, verbose_name='Категория Ур.2')),
                ('category_2_zh', models.CharField(blank=True, max_length=255, verbose_name='Категория Ур.2 (CN)')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование товара')),
                ('name_zh', models.CharField(blank=True, max_length=500, verbose_name='Наименование товара (CN)')),
                ('composition', models.TextField(blank=True, verbose_name='Состав')),
                ('composition_zh', models.TextField(blank=True, verbose_name='Состав (CN)')),
                ('photos_list', models.JSONField(blank=True, default=list, verbose_name='Список фото')),
                ('video_link', models.URLField(blank=True, max_length=500, verbose_name='Видео (ссылка)')),
                ('size_goods', models.CharField(blank=True, max_length=255, verbose_name='Размер товара')),
                ('package_goods', models.CharField(blank=True, max_length=255, verbose_name='Упаковка товара')),
                ('group_package', models.CharField(blank=True, max_length=255, verbose_name='Групповая упаковка')),
                ('quantum', models.IntegerField(default=0, verbose_name='Квант')),
                ('price_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фактическая цена, ₽')),
                ('transport_box_load', models.CharField(blank=True, max_length=255, verbose_name='Загрузка транспортного короба')),
                ('width_cm', models.FloatField(default=0, verbose_name='Width, cm')),
                ('height_cm', models.FloatField(default=0, verbose_name='Height, cm')),
                ('length_cm', models.FloatField(default=0, verbose_name='Length, cm')),
                ('cbm', models.FloatField(default=0, verbose_name='CBM')),
                ('gross_weight', models.FloatField(default=0, verbose_name='Брутто трансп. короба')),
                ('tn_ved_code', models.CharField(blank=True, max_length=50, verbose_name='ТН ВЭД код')),
                ('tp', models.CharField(blank=True, max_length=50, verbose_name='ТП')),
                ('rd', models.CharField(blank=True, max_length=50, verbose_name='РД')),
                ('risk', models.CharField(blank=True, max_length=50, verbose_name='Риск')),
                ('vat', models.CharField(default='20%', max_length=20, verbose_name='НДС')),
                ('amount_stores', models.IntegerField(default=0, verbose_name='Кол-во магазинов')),
                ('amount_pieces', models.IntegerField(default=0, verbose_name='Кол-во шт')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('comments_zh', models.TextField(blank=True, verbose_name='Комментарии (CN)')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-id'],
            },
        ),
    ]
