# Generated by Django 5.0.1 on 2025-12-25 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата КП'),
        ),
    ]
