# Generated by Django 5.0.1 on 2026-01-03 07:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0002_alter_product_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_goods_zh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Упаковка товара (CN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='rd_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='РД (CN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='risk_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='Риск (CN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tp_zh',
            field=models.CharField(blank=True, max_length=100, verbose_name='ТП (CN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rd',
            field=models.CharField(blank=True, max_length=100, verbose_name='РД'),
        ),
        migrations.AlterField(
            model_name='product',
            name='risk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Риск'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tp',
            field=models.CharField(blank=True, max_length=100, verbose_name='ТП'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['article'], name='idx_art_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_name_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_zh'], name='idx_name_zh_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['category_1'], name='idx_c1_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['category_2'], name='idx_c2_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['composition'], name='idx_comp_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tp'], name='idx_tp_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['rd'], name='idx_rd_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['risk'], name='idx_risk_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
