upstream api_upstream {
    server web:8000;
}

# 1. Редирект с HTTP на HTTPS
server {
    listen 80;
    server_name 37.77.104.201.sslip.io;
    return 301 https://$host$request_uri;
}

# 2. Основной сервер HTTPS
server {
    listen 443 ssl;
    server_name 37.77.104.201.sslip.io;

    client_max_body_size 100M;

    proxy_read_timeout 1200s;
    proxy_connect_timeout 1200s;
    proxy_send_timeout 1200s;
    client_body_timeout 1200s;
    keepalive_timeout 1200s;


    # Пути к сертификатам
    ssl_certificate /etc/letsencrypt/live/37.77.104.201.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/37.77.104.201.sslip.io/privkey.pem;

    # Настройки SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Статика
    location /static/ {
        alias /app/staticfiles/;
    }

    # Медиа
    location /media/ {
        alias /app/media/;
    }

    # API
    location /api/ {
        # Просто передаем запрос на бэкенд
        proxy_pass http://api_upstream;


        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    # Админка
    location /admin/ {
        proxy_pass http://api_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Фронтенд
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}